In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

a = np.arange(12, 24)

In [3]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.

In [4]:
b1 = a.reshape(3,4)
c1 = a.reshape(2,6)
d1 = a.reshape(4,3)
e1 = a.reshape(6,2)
f1 = a.reshape(1,12)

In [5]:
print(b1)
print(c1)
print(d1)
print(e1)
print(f1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).

In [6]:
b2 = a.reshape(3,-1)
c2 = a.reshape(2,-1)
d2 = a.reshape(4,-1)
e2 = a.reshape(-1,2)
f2 = a.reshape(-1,12)

In [7]:
print(b2)
print(c2)
print(d2)
print(e2)
print(f2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нельзя массив, состоящий из одного столбца и 12 строк, назвать одномерным, т.к. он имеет другую структуру:

In [8]:
b3 = a.reshape(12,1)
print(b3)
print(b3[7,0]) # выбор элемента в 2-ом массиве отличается от выбора в одномерном
print(a[7])

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
19
19


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.

In [9]:
arr = np.random.randn(3, 4)

In [10]:
print(arr)

[[ 0.73729942  0.07337972  2.27007179  1.96342955]
 [ 0.83237086 -1.41298056  1.39131881 -0.9767819 ]
 [ 1.12933663  1.39990315  0.35299219 -0.20373328]]


In [11]:
arr2 = arr.flatten()

In [12]:
print(arr2)

[ 0.73729942  0.07337972  2.27007179  1.96342955  0.83237086 -1.41298056
  1.39131881 -0.9767819   1.12933663  1.39990315  0.35299219 -0.20373328]


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.

In [13]:
a = np.arange(20, 0, -2)

In [14]:
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?

In [15]:
b = np.arange(20, 1, -2).reshape(1,10)

In [16]:
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


Разница в структуре, и соответственно, в доступе к элементам

In [17]:
print(a[5])
print(b[0,5])

10
10


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [18]:
a = np.array([[0,0],
           [0,0]])
b= np.array([[1,1],
            [1,1],
            [1,1]])

In [19]:
v = np.vstack((a, b))

In [20]:
print(v)
print(v.size)

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]
10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [21]:
a = np.arange(0,12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
A = a.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
At = A.T

In [24]:
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [25]:
B = A.dot(At)
print(B)
print(B.size)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
16


Если матрица квадратная, то мы можем посчитать её определитель. Обратную матрицу можно посчитать только для матрицы, определитель которой не равен 0


In [26]:
d = np.linalg.det(B)
print(d)

0.0


Т.к. определитель=0, то здесь вычислить обратную матрицу для матрицы B мы не можем
#B_inv = np.linalg.inv(B)

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [27]:
 np.random.seed(42)    

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

In [28]:
c = np.random.randint(0, 16, 16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [29]:
C = c.reshape(4,4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [30]:
D = B + (C * 10)
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [31]:
d_D = np.linalg.det(D)
print(d_D)

-28511999.999999944


In [32]:
r_D = np.linalg.matrix_rank(D)
print(r_D)

4


In [33]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [34]:
D_inv = np.where(D_inv < 0, 0, 1)
print(D_inv)


[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [35]:
E = np.where(D_inv,B,C)
print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
